repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: poetry run pytest
        language: system
        pass_filenames: false

      - id: commitlint
        name: Commitlint
        entry: python -m src.commitlint.cli --file
        language: python
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
