name: 'Conventional Commitlint'
description: 'A GitHub Action to check conventional commit message'
inputs:
  fail_on_error:
    description: Whether to fail the workflow if commit messages don't follow conventions.
    default: 'true'
    required: false
  verbose:
    description: Verbose output.
    default: 'false'
    required: false
outputs:
  status:
    description: Status
    value: ${{ steps.commitlint.outputs.status }}
  exit_code:
    description: Exit Code
    value: ${{ steps.commitlint.outputs.exit_code }}
branding:
  color: 'red'
  icon: 'git-commit'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8'

    - name: Install Commitlint
      run: python -m pip install --disable-pip-version-check -e ${{ github.action_path }}
      shell: bash

    # checkout to the source code
    # for push event
    - name: Get pushed commit count
      if: github.event_name == 'push'
      id: push_commit_count
      run: |
        echo "count=$(echo '${{ toJson(github.event.commits) }}' | jq '. | length')" \
          >> $GITHUB_OUTPUT
      shell: bash

    - name: Checkout to pushed commits
      if: github.event_name == 'push'
      uses: actions/checkout@v4.1.7
      with:
        ref: ${{ github.sha }}
        fetch-depth: ${{ steps.push_commit_count.outputs.count }}

    # for pull_request event
    - name: Checkout to PR source branch
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v4.1.7
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ github.event.pull_request.commits }}

    # checking the commits (for both push and pull_request)
    - name: Check the commits
      id: commitlint
      run: |
        python ${{ github.action_path }}/github_actions/run.py
      shell: bash
      env:
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
