name: 'Conventional Commitlint'
description: 'A GitHub Action to check conventional commit message'

inputs:
  fail_on_error:
    description: Whether to fail the workflow if commit messages don't follow conventions.
    default: 'true'
    required: false
  verbose:
    description: Verbose output.
    default: 'false'
    required: false
  token:
    description: Token for fetching commits using Github API.
    default: ${{ github.token }}
    required: false

outputs:
  status:
    description: Status
    value: ${{ steps.commitlint.outputs.status }}
  exit_code:
    description: Exit Code
    value: ${{ steps.commitlint.outputs.exit_code }}

branding:
  color: 'red'
  icon: 'git-commit'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10'

    - name: Commitlint Action
      id: commitlint
      run: |
        python -m pip install --quiet --disable-pip-version-check -e ${GITHUB_ACTION_PATH}
        python ${{ github.action_path }}/github_actions
      shell: bash
      env:
        # NOTE: Remove once https://github.com/actions/runner/issues/665 is fixed.
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
